### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by banks256**
Project of such nature can eradicated poverty and solve the increasing number of unemployment among the youths in communities.

### CODE REVIEW

**Comment by banks256** [comment]
Positive change

**Comment by banks256** [comment]
Open source technology, if funded seems to be a poverty eradicating  idea in the near future

**Comment by banks256** [comment]
Materials for building FM radio ,1 capacitors 10volts ,6.3volts,2 station box,2coils(2),3transistors(power and sound)4 jumper wires,5 resistors(R1,R2,R3,R4,R5 etc depending on the type of radio we intend to build)

**Comment by chardso** [comment]
Its fm/mW/sw radio building, am so far left with two steps to conclude the whole session.

**Pull request merged**
